services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muse_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      CI_ENVIRONMENT: development